modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "colemakcaps"
version = "${version}"
displayName = "colemakCaps"
authors = "TheTreeSee"
description = '''
Restores caps lock as backspace for the 6 Colemak backspace users in Minecraft.
'''
logoFile = "assets/colemakcaps/icon.png"

[[dependencies.colemakcaps]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colemakcaps]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colemakcaps]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "colemakcaps.mixins.json"
